twig:
    globals:
      BaseInfo: null
      eccube_config: '@Eccube\Common\EccubeConfig'
    paths:
      '%eccube_theme_front_dir%': ~
      '%eccube_theme_front_default_dir%': ~
      '%kernel.project_dir%/app/Plugin': ~
      '%eccube_theme_admin_dir%': admin
      '%eccube_theme_admin_default_dir%': admin
      '%eccube_theme_user_data_dir%': user_data
      '%eccube_theme_src_dir%/toolbar': toolbar
      '%eccube_theme_src_dir%/common': common
#      '%eccube_theme_app_dir%' : customize
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    date:
      timezone: '%timezone%'
